In [1]:
import pandas as pd

df = pd.read_csv("../data/df_Products.csv")
df.head()

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0

In [2]:
df.shape

(89316, 6)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             89316 non-null  object
 1   product_category_name  89008 non-null  object
 2   product_weight_g       89301 non-null  float64
 3   product_length_cm      89301 non-null  float64
 4   product_height_cm      89301 non-null  float64
 5   product_width_cm       89301 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.1+ MB

In [4]:
df.isnull().sum()

product_id                 0
product_category_name    308
product_weight_g          15
product_length_cm         15
product_height_cm         15
product_width_cm          15
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(61865)

In [6]:
df[df["product_category_name"].isnull()]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
329,6cDVtksZH7KU,NaN,200.0,16.0,2.0,11.0
1037,z6g5uM3fiCVO,NaN,300.0,30.0,6.0,12.0
1179,N6XMQZiwCJ3t,NaN,600.0,24.0,4.0,15.0
1589,W3IIy0dnIfkU,NaN,200.0,16.0,2.0,11.0
3061,Z2X9RgoeYqaj,NaN,6250.0,28.0,34.0,40.0
...,...,...,...,...,...,...
88099,5gjt2T2OSHe3,NaN,200.0,22.0,14.0,14.0
88282,RlHxglMXV69Y,NaN,200.0,16.0,10.0,13.0
88312,vLQWWPXCmqA7,NaN,300.0,35.0,7.0,12.0
88640,nAfiZ93td5vY,NaN,17100.0,42.0,80.0,30.0
89021,pWoCB3wduEGo,NaN,1000.0,20.0,15.0,20.0

In [7]:
df[
    df["product_weight_g"].isnull() |
    df["product_length_cm"].isnull() |
    df["product_height_cm"].isnull() |
    df["product_width_cm"].isnull()
]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
2150,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
7473,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
13628,VqyFCmRtRdfR,toys,NaN,NaN,NaN,NaN
28114,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
32791,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
38130,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
39021,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
49124,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
55696,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
56195,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
57156,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
63531,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
68946,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
70321,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
88303,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN

In [8]:
df.isnull().sum(axis=1).value_counts()

0    88993
1      308
4       15
Name: count, dtype: int64

In [9]:
df.shape

(89316, 6)

In [10]:
df["product_id"].nunique()

27451

In [11]:
df["product_id"].duplicated().sum()

np.int64(61865)

In [12]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Unique products:", df["product_id"].nunique())

Rows: 89316
Columns: 6
Unique products: 27451

In [13]:
df["product_id"].value_counts().head(10)

product_id
0vbEvli2JYJu    405
9NwzO0Pm0fDM    383
UgkSjxoiV9Ev    383
SLTlrWtcYt1m    321
Biwi1BNtUB7l    295
ro08JPncYzLh    290
1edaUIVffPFF    255
sCONCvmO1cEY    242
dAz11YkQkoue    227
Ffe8gTdmyO3U    209
Name: count, dtype: int64

In [14]:
duplicate_rows = df[df.duplicated(keep=False)]

duplicate_rows.head(20)

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0
5,TpFZIk33uyGn,toys,2800.0,16.0,31.0,39.0
6,Y0T4Ca4BXK8U,bed_bath_table,3975.0,46.0,12.0,43.0
8,0UHKKyYmxWfq,toys,1200.0,30.0,23.0,30.0
9,MJ82dNJNiV7U,toys,1500.0,30.0,5.0,20.0
10,wdV7yJzaz3Su,toys,4338.0,17.0,12.0,14.0
11,V3ksL8RRt2uO,toys,350.0,21.0,22.0,22.0
12,vndXhZ66Bwpl,toys,500.0,16.0,12.0,22.0
13,2RxPIb6Sjlm1,toys,300.0,38.0,19.0,22.0
14,DXG0TFaZjGHO,toys,200.0,16.0,7.0,11.0
16,CBuRjOln99hg,auto,350.0,20.0,15.0,15.0
17,tfgKHMdnTKpJ,toys,425.0,17.0,11.0,14.0
18,l0Q038BC2u3G,health_beauty,4200.0,30.0,10.0,20.0
20,E9OiMOkPkNam,toys,335.0,17.0,11.0,16.0
21,aYw1jx6U0ZzQ,toys,300.0,27.0,25.0,27.0
22,kuUbPNBMgk7o,toys,2150.0,30.0,19.0,25.0

In [15]:
duplicate_rows["product_id"].value_counts().head(10)

product_id
0vbEvli2JYJu    405
UgkSjxoiV9Ev    383
9NwzO0Pm0fDM    383
SLTlrWtcYt1m    321
Biwi1BNtUB7l    295
ro08JPncYzLh    290
1edaUIVffPFF    255
sCONCvmO1cEY    242
dAz11YkQkoue    227
Ffe8gTdmyO3U    209
Name: count, dtype: int64

In [16]:
print("Rows:", len(df))
print("Unique products:", df["product_id"].nunique())
print("Duplicate product IDs:", df["product_id"].duplicated().sum())

Rows: 89316
Unique products: 27451
Duplicate product IDs: 61865

In [17]:
df.isnull().sum(axis=1).value_counts()

0    88993
1      308
4       15
Name: count, dtype: int64

In [18]:
df["product_id"].value_counts().head(10)

product_id
0vbEvli2JYJu    405
9NwzO0Pm0fDM    383
UgkSjxoiV9Ev    383
SLTlrWtcYt1m    321
Biwi1BNtUB7l    295
ro08JPncYzLh    290
1edaUIVffPFF    255
sCONCvmO1cEY    242
dAz11YkQkoue    227
Ffe8gTdmyO3U    209
Name: count, dtype: int64

In [19]:
df[df.duplicated(keep=False)].head(20)

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0
5,TpFZIk33uyGn,toys,2800.0,16.0,31.0,39.0
6,Y0T4Ca4BXK8U,bed_bath_table,3975.0,46.0,12.0,43.0
8,0UHKKyYmxWfq,toys,1200.0,30.0,23.0,30.0
9,MJ82dNJNiV7U,toys,1500.0,30.0,5.0,20.0
10,wdV7yJzaz3Su,toys,4338.0,17.0,12.0,14.0
11,V3ksL8RRt2uO,toys,350.0,21.0,22.0,22.0
12,vndXhZ66Bwpl,toys,500.0,16.0,12.0,22.0
13,2RxPIb6Sjlm1,toys,300.0,38.0,19.0,22.0
14,DXG0TFaZjGHO,toys,200.0,16.0,7.0,11.0
16,CBuRjOln99hg,auto,350.0,20.0,15.0,15.0
17,tfgKHMdnTKpJ,toys,425.0,17.0,11.0,14.0
18,l0Q038BC2u3G,health_beauty,4200.0,30.0,10.0,20.0
20,E9OiMOkPkNam,toys,335.0,17.0,11.0,16.0
21,aYw1jx6U0ZzQ,toys,300.0,27.0,25.0,27.0
22,kuUbPNBMgk7o,toys,2150.0,30.0,19.0,25.0

In [20]:
df["product_id"].nunique()

27451

In [21]:
len(df)

89316

In [22]:
df = df.drop_duplicates()

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df["product_id"].duplicated().sum()

np.int64(0)

In [25]:
df["product_id"].nunique()

27451

In [26]:
len(df)

27451

In [27]:
df.isnull().sum()

product_id                 0
product_category_name    141
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
dtype: int64

In [28]:
df[
    (df["product_weight_g"] <= 0) |
    (df["product_length_cm"] <= 0) |
    (df["product_height_cm"] <= 0) |
    (df["product_width_cm"] <= 0)
]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1476,fsq5lo34nHGK,toys,0.0,30.0,25.0,30.0
51136,aMbBkxpim3xt,toys,0.0,30.0,25.0,30.0
65518,nm5AMMVOx4Ac,toys,0.0,30.0,25.0,30.0
83528,xUlGNJzxYn1N,toys,0.0,30.0,25.0,30.0

In [29]:
df["product_category_name"].value_counts().head(20)

product_category_name
toys                        20609
bed_bath_table                654
sports_leisure                624
furniture_decor               567
health_beauty                 530
housewares                    513
auto                          384
computers_accessories         363
watches_gifts                 266
telephony                     257
baby                          208
stationery                    191
fashion_bags_accessories      190
perfumery                     189
cool_stuff                    169
pet_shop                      154
garden_tools                  147
electronics                   133
office_furniture               86
luggage_accessories            86
Name: count, dtype: int64

In [30]:
df["product_category_name"].nunique()

70

In [31]:
df = df.drop_duplicates()

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df["product_id"].duplicated().sum()

np.int64(0)

In [34]:
print("Rows:", len(df))
print("Unique products:", df["product_id"].nunique())

Rows: 27451
Unique products: 27451

In [35]:
df.isnull().sum()

product_id                 0
product_category_name    141
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
dtype: int64

In [36]:
df["product_category_name"] = (
    df["product_category_name"].fillna("Unknown")
)

In [37]:
df["product_category_name"].isnull().sum()

np.int64(0)

In [38]:
df[
    df["product_weight_g"].isnull() |
    df["product_length_cm"].isnull() |
    df["product_height_cm"].isnull() |
    df["product_width_cm"].isnull()
]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
2150,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
13628,VqyFCmRtRdfR,toys,NaN,NaN,NaN,NaN

In [39]:
df[
    (df["product_weight_g"] <= 0) |
    (df["product_length_cm"] <= 0) |
    (df["product_height_cm"] <= 0) |
    (df["product_width_cm"] <= 0)
]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1476,fsq5lo34nHGK,toys,0.0,30.0,25.0,30.0
51136,aMbBkxpim3xt,toys,0.0,30.0,25.0,30.0
65518,nm5AMMVOx4Ac,toys,0.0,30.0,25.0,30.0
83528,xUlGNJzxYn1N,toys,0.0,30.0,25.0,30.0

In [40]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate product IDs:", df["product_id"].duplicated().sum())
print("Rows:", len(df))
print("Unique products:", df["product_id"].nunique())

Duplicate rows: 0
Duplicate product IDs: 0
Rows: 27451
Unique products: 27451

In [41]:
df["product_category_name"] = (
    df["product_category_name"].fillna("Unknown")
)

In [42]:
df[
    df["product_weight_g"].isnull() |
    df["product_length_cm"].isnull() |
    df["product_height_cm"].isnull() |
    df["product_width_cm"].isnull()
]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
2150,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
13628,VqyFCmRtRdfR,toys,NaN,NaN,NaN,NaN

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27451 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             27451 non-null  object
 1   product_category_name  27451 non-null  object
 2   product_weight_g       27449 non-null  float64
 3   product_length_cm      27449 non-null  float64
 4   product_height_cm      27449 non-null  float64
 5   product_width_cm       27449 non-null  float64
dtypes: float64(4), object(2)
memory usage: 1.5+ MB

In [44]:
df.describe(include="all")

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,27451,27451,27449.000000,27449.000000,27449.000000,27449.000000
unique,27451,71,NaN,NaN,NaN,NaN
top,90K0C1fIyQUf,toys,NaN,NaN,NaN,NaN
freq,1,20609,NaN,NaN,NaN,NaN
mean,NaN,NaN,2249.476994,30.714015,16.896426,23.122045
std,NaN,NaN,4219.591017,16.805513,13.633966,12.008406
min,NaN,NaN,0.000000,7.000000,2.000000,6.000000
25%,NaN,NaN,300.000000,18.000000,8.000000,15.000000
50%,NaN,NaN,700.000000,25.000000,13.000000,20.000000
75%,NaN,NaN,1850.000000,38.000000,20.000000,30.000000
max,NaN,NaN,40425.000000,105.000000,105.000000,118.000000

In [45]:
df.to_csv(
    "cleaned_products.csv",
    index=False
)