In [2]:
import pandas as pd

df = pd.read_csv("../data/df_Orders.csv")
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18

In [3]:
df.shape

(89316, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  object
 4   order_approved_at              89307 non-null  object
 5   order_delivered_timestamp      87427 non-null  object
 6   order_estimated_delivery_date  89316 non-null  object
dtypes: object(7)
memory usage: 4.8+ MB

In [5]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
dtype: int64

In [6]:
df["order_status"].value_counts()

order_status
delivered      87428
shipped          936
canceled         409
processing       273
invoiced         266
unavailable        2
approved           2
Name: count, dtype: int64

In [7]:
df[df["order_delivered_timestamp"].isnull()]["order_status"].value_counts()

order_status
shipped        936
canceled       404
processing     273
invoiced       266
delivered        6
unavailable      2
approved         2
Name: count, dtype: int64

In [8]:
df[df["order_approved_at"].isnull()]["order_status"].value_counts()

order_status
delivered    9
Name: count, dtype: int64

In [9]:
df[df["order_approved_at"].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
10788,4Itts2TBUQzs,Z3dI7uRBfJOD,delivered,2017-02-17 13:05:55,NaN,2017-03-02 11:09:19,2017-03-20
16137,6MPB830Ufh0n,SOtqXN1MqcLj,delivered,2017-02-17 17:21:55,NaN,2017-03-03 12:16:03,2017-03-20
28951,lqW95yj4n1Qd,jCPmhkcyVR1z,delivered,2017-02-18 15:52:27,NaN,2017-03-07 13:57:47,2017-03-29
30494,dn1i9D4DFVZ2,Es95IGZCDDXy,delivered,2017-02-17 15:53:27,NaN,2017-03-03 11:47:47,2017-03-23
41752,vBZCEuCG9Hf1,zHEH7vdeO6UZ,delivered,2017-02-18 11:04:19,NaN,2017-03-02 16:15:23,2017-03-22
42772,PXwPIjmXCehX,gjKhFw8AFnW1,delivered,2017-02-18 16:48:35,NaN,2017-03-09 07:28:47,2017-03-31
47768,Yg9HDkWtA3Q3,GFg4QWN26cLs,delivered,2017-02-19 01:28:47,NaN,2017-03-02 03:41:58,2017-03-27
59434,hynO4uEubWbe,QdQBjy8APVMg,delivered,2017-02-18 14:40:00,NaN,2017-03-01 13:25:33,2017-03-17
65247,Uso7EoEPMrLU,rKJOxQc2PTfc,delivered,2017-01-19 22:26:59,NaN,2017-02-06 14:22:19,2017-03-16

In [10]:
(df.isnull().sum() / len(df) * 100).round(2)

order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.01
order_delivered_timestamp        2.11
order_estimated_delivery_date    0.00
dtype: float64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["order_id"].duplicated().sum()

np.int64(0)

In [13]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_timestamp",
    "order_estimated_delivery_date"
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [14]:
df.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_timestamp        datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [15]:
df[df["order_delivered_timestamp"].isnull()]["order_status"].value_counts()

order_status
shipped        936
canceled       404
processing     273
invoiced       266
delivered        6
unavailable      2
approved         2
Name: count, dtype: int64

In [16]:
df[df["order_status"].eq("delivered") &
   df["order_delivered_timestamp"].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
4254,t5kBjEdw3z8t,ZeIXZ7BBF5PP,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,NaT,2017-12-18
13268,BxxG20QRNt7K,RWhfv6bIMVsQ,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,NaT,2018-07-16
30892,yRSiD6TjWuMp,WrJg7MJuozgD,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,NaT,2018-07-30
65263,1XWJAxXBtYuW,Z5AHwQM14J3A,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,NaT,2018-06-26
65525,H6OIR9EVCoos,53rYCxN5t4tp,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,NaT,2018-07-19
67317,EznMwXRSIZcm,RMR2x4OEJS2K,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,NaT,2018-07-30

In [17]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_timestamp",
    "order_estimated_delivery_date"
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [18]:
df.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_timestamp        datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [19]:
(df["order_approved_at"] < df["order_purchase_timestamp"]).sum()

np.int64(0)

In [20]:
(df["order_delivered_timestamp"] < df["order_purchase_timestamp"]).sum()

np.int64(0)

In [23]:
(df["order_estimated_delivery_date"] <
 df["order_purchase_timestamp"]).sum()

np.int64(0)

In [24]:
df[df["order_status"].eq("delivered") &
   df["order_delivered_timestamp"].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,delivery_delay_days
4254,t5kBjEdw3z8t,ZeIXZ7BBF5PP,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,NaT,2017-12-18,NaN
13268,BxxG20QRNt7K,RWhfv6bIMVsQ,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,NaT,2018-07-16,NaN
30892,yRSiD6TjWuMp,WrJg7MJuozgD,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,NaT,2018-07-30,NaN
65263,1XWJAxXBtYuW,Z5AHwQM14J3A,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,NaT,2018-06-26,NaN
65525,H6OIR9EVCoos,53rYCxN5t4tp,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,NaT,2018-07-19,NaN
67317,EznMwXRSIZcm,RMR2x4OEJS2K,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,NaT,2018-07-30,NaN

In [25]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_timestamp",
    "order_estimated_delivery_date"
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [26]:
(df["order_approved_at"] < df["order_purchase_timestamp"]).sum()

np.int64(0)

In [27]:
(df["order_delivered_timestamp"] < df["order_purchase_timestamp"]).sum()

np.int64(0)

In [28]:
(df["order_estimated_delivery_date"] <
 df["order_purchase_timestamp"]).sum()

np.int64(0)

In [29]:
df.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_timestamp        datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
delivery_delay_days                     float64
dtype: object

In [30]:
df["delivery_delay_days"].describe()

count    87427.000000
mean       -12.132442
std         10.041470
min       -147.000000
25%        -17.000000
50%        -13.000000
75%         -7.000000
max        188.000000
Name: delivery_delay_days, dtype: float64

In [31]:
df["delivery_delay_days"].isnull().sum()

np.int64(1889)

In [32]:
df["delivery_delay_days"].head(10)

0   -14.0
1   -21.0
2    -9.0
3   -23.0
4   -13.0
5   -11.0
6    -9.0
7    18.0
8    -3.0
9   -20.0
Name: delivery_delay_days, dtype: float64

In [33]:
df[
    (df["order_status"] == "delivered") &
    (df["order_delivered_timestamp"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,delivery_delay_days
4254,t5kBjEdw3z8t,ZeIXZ7BBF5PP,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,NaT,2017-12-18,NaN
13268,BxxG20QRNt7K,RWhfv6bIMVsQ,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,NaT,2018-07-16,NaN
30892,yRSiD6TjWuMp,WrJg7MJuozgD,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,NaT,2018-07-30,NaN
65263,1XWJAxXBtYuW,Z5AHwQM14J3A,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,NaT,2018-06-26,NaN
65525,H6OIR9EVCoos,53rYCxN5t4tp,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,NaT,2018-07-19,NaN
67317,EznMwXRSIZcm,RMR2x4OEJS2K,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,NaT,2018-07-30,NaN

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df["order_status"].value_counts()

order_status
delivered      87428
shipped          936
canceled         409
processing       273
invoiced         266
unavailable        2
approved           2
Name: count, dtype: int64

In [38]:
df["customer_id"].isin(df["customer_id"]).value_counts()

customer_id
True    89316
Name: count, dtype: int64

In [39]:
df["delivery_delay_days"] = (
    df["order_delivered_timestamp"]
    - df["order_estimated_delivery_date"]
).dt.days

In [40]:
# 1. Investigate 6 delivered orders with missing delivery date
df[
    (df["order_status"] == "delivered") &
    (df["order_delivered_timestamp"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,delivery_delay_days
4254,t5kBjEdw3z8t,ZeIXZ7BBF5PP,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,NaT,2017-12-18,NaN
13268,BxxG20QRNt7K,RWhfv6bIMVsQ,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,NaT,2018-07-16,NaN
30892,yRSiD6TjWuMp,WrJg7MJuozgD,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,NaT,2018-07-30,NaN
65263,1XWJAxXBtYuW,Z5AHwQM14J3A,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,NaT,2018-06-26,NaN
65525,H6OIR9EVCoos,53rYCxN5t4tp,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,NaT,2018-07-19,NaN
67317,EznMwXRSIZcm,RMR2x4OEJS2K,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,NaT,2018-07-30,NaN

In [41]:
# 2. Duplicate rows
df.duplicated().sum()

np.int64(0)

In [42]:
# 3. Duplicate order IDs
df["order_id"].duplicated().sum()

np.int64(0)

In [44]:
# 4. Orders → Customers relationship
df["customer_id"].isin(df["customer_id"]).value_counts()

customer_id
True    89316
Name: count, dtype: int64

In [45]:
df.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_timestamp        datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
delivery_delay_days                     float64
dtype: object

In [47]:
df = df.drop(columns=["delivery_delay_days"])

In [48]:
df.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_timestamp        datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [49]:
df.to_csv(
    "cleaned_orders.csv",
    index=False
)